apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: tomcat-test
spec:
  storageClassName: hostpath   # ★ 현재 클러스터가 실제로 쓰는 SC
  accessModes:
    - ReadWriteOnce            # hostpath는 보통 RWO만 지원
  resources:
    requests:
      storage: 10Gi

